/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LEVITREE_DEVICE_ADC_PB_H_INCLUDED
#define PB_LEVITREE_DEVICE_ADC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _levitree_ADCCommandRequest {
    char dummy_field;
} levitree_ADCCommandRequest;

typedef struct _levitree_ADCCommandResponse {
    char dummy_field;
} levitree_ADCCommandResponse;

typedef struct _levitree_ADCChannelValue {
    int32_t channel_number;
    int32_t adc_value;
} levitree_ADCChannelValue;

typedef struct _levitree_ADCState {
    pb_size_t values_count;
    levitree_ADCChannelValue values[8];
} levitree_ADCState;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define levitree_ADCCommandRequest_init_default  {0}
#define levitree_ADCCommandResponse_init_default {0}
#define levitree_ADCChannelValue_init_default    {0, 0}
#define levitree_ADCState_init_default           {0, {levitree_ADCChannelValue_init_default, levitree_ADCChannelValue_init_default, levitree_ADCChannelValue_init_default, levitree_ADCChannelValue_init_default, levitree_ADCChannelValue_init_default, levitree_ADCChannelValue_init_default, levitree_ADCChannelValue_init_default, levitree_ADCChannelValue_init_default}}
#define levitree_ADCCommandRequest_init_zero     {0}
#define levitree_ADCCommandResponse_init_zero    {0}
#define levitree_ADCChannelValue_init_zero       {0, 0}
#define levitree_ADCState_init_zero              {0, {levitree_ADCChannelValue_init_zero, levitree_ADCChannelValue_init_zero, levitree_ADCChannelValue_init_zero, levitree_ADCChannelValue_init_zero, levitree_ADCChannelValue_init_zero, levitree_ADCChannelValue_init_zero, levitree_ADCChannelValue_init_zero, levitree_ADCChannelValue_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define levitree_ADCChannelValue_channel_number_tag 1
#define levitree_ADCChannelValue_adc_value_tag   2
#define levitree_ADCState_values_tag             3

/* Struct field encoding specification for nanopb */
#define levitree_ADCCommandRequest_FIELDLIST(X, a) \

#define levitree_ADCCommandRequest_CALLBACK NULL
#define levitree_ADCCommandRequest_DEFAULT NULL

#define levitree_ADCCommandResponse_FIELDLIST(X, a) \

#define levitree_ADCCommandResponse_CALLBACK NULL
#define levitree_ADCCommandResponse_DEFAULT NULL

#define levitree_ADCChannelValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    channel_number,    1) \
X(a, STATIC,   SINGULAR, INT32,    adc_value,         2)
#define levitree_ADCChannelValue_CALLBACK NULL
#define levitree_ADCChannelValue_DEFAULT NULL

#define levitree_ADCState_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  values,            3)
#define levitree_ADCState_CALLBACK NULL
#define levitree_ADCState_DEFAULT NULL
#define levitree_ADCState_values_MSGTYPE levitree_ADCChannelValue

extern const pb_msgdesc_t levitree_ADCCommandRequest_msg;
extern const pb_msgdesc_t levitree_ADCCommandResponse_msg;
extern const pb_msgdesc_t levitree_ADCChannelValue_msg;
extern const pb_msgdesc_t levitree_ADCState_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define levitree_ADCCommandRequest_fields &levitree_ADCCommandRequest_msg
#define levitree_ADCCommandResponse_fields &levitree_ADCCommandResponse_msg
#define levitree_ADCChannelValue_fields &levitree_ADCChannelValue_msg
#define levitree_ADCState_fields &levitree_ADCState_msg

/* Maximum encoded size of messages (where known) */
#define LEVITREE_DEVICE_ADC_PB_H_MAX_SIZE        levitree_ADCState_size
#define levitree_ADCChannelValue_size            22
#define levitree_ADCCommandRequest_size          0
#define levitree_ADCCommandResponse_size         0
#define levitree_ADCState_size                   192

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
