/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LEVITREE_DEVICE_VFD_PB_H_INCLUDED
#define PB_LEVITREE_DEVICE_VFD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _levitree_VFDDriveMode {
    levitree_VFDDriveMode_VFD_DRIVE_MODE_UNSPECIFIED = 0,
    levitree_VFDDriveMode_VFD_DRIVE_MODE_STOP = 1,
    levitree_VFDDriveMode_VFD_DRIVE_MODE_FORWARD = 2,
    levitree_VFDDriveMode_VFD_DRIVE_MODE_REVERSE = 3
} levitree_VFDDriveMode;

typedef enum _levitree_VFDFailSafeMode {
    levitree_VFDFailSafeMode_VFD_FAIL_SAFE_MODE_UNSPECIFIED = 0,
    levitree_VFDFailSafeMode_VFD_FAIL_SAFE_MODE_RAMP_DOWN = 1,
    levitree_VFDFailSafeMode_VFD_FAIL_SAFE_MODE_E_STOP = 2,
    levitree_VFDFailSafeMode_VFD_FAIL_SAFE_MODE_NONE = 3
} levitree_VFDFailSafeMode;

/* Struct definitions */
typedef struct _levitree_VFDCommandResponse {
    char dummy_field;
} levitree_VFDCommandResponse;

typedef struct _levitree_VFDState {
    float frequency_hz;
    float power_w;
    float current_a;
    float voltage_v;
    levitree_VFDDriveMode drive_mode;
    levitree_VFDFailSafeMode fail_safe_mode;
    int32_t alarm_code;
} levitree_VFDState;

typedef struct _levitree_SetFailSafeRequest {
    levitree_VFDFailSafeMode mode;
} levitree_SetFailSafeRequest;

typedef struct _levitree_SetDriveModeRequest {
    levitree_VFDDriveMode drive_mode;
} levitree_SetDriveModeRequest;

typedef struct _levitree_SetFrequencyRequest {
    float frequency_hz;
} levitree_SetFrequencyRequest;

typedef struct _levitree_ClearAlarmRequest { /* This message can be empty, as it just indicates a request to clear alarms. */
    char dummy_field;
} levitree_ClearAlarmRequest;

typedef struct _levitree_VFDCommandRequest {
    pb_size_t which_command;
    union {
        levitree_SetFailSafeRequest set_fail_safe;
        levitree_SetDriveModeRequest set_drive_mode;
        levitree_SetFrequencyRequest set_frequency;
        levitree_ClearAlarmRequest clear_alarm;
    } command;
} levitree_VFDCommandRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _levitree_VFDDriveMode_MIN levitree_VFDDriveMode_VFD_DRIVE_MODE_UNSPECIFIED
#define _levitree_VFDDriveMode_MAX levitree_VFDDriveMode_VFD_DRIVE_MODE_REVERSE
#define _levitree_VFDDriveMode_ARRAYSIZE ((levitree_VFDDriveMode)(levitree_VFDDriveMode_VFD_DRIVE_MODE_REVERSE+1))

#define _levitree_VFDFailSafeMode_MIN levitree_VFDFailSafeMode_VFD_FAIL_SAFE_MODE_UNSPECIFIED
#define _levitree_VFDFailSafeMode_MAX levitree_VFDFailSafeMode_VFD_FAIL_SAFE_MODE_NONE
#define _levitree_VFDFailSafeMode_ARRAYSIZE ((levitree_VFDFailSafeMode)(levitree_VFDFailSafeMode_VFD_FAIL_SAFE_MODE_NONE+1))



#define levitree_VFDState_drive_mode_ENUMTYPE levitree_VFDDriveMode
#define levitree_VFDState_fail_safe_mode_ENUMTYPE levitree_VFDFailSafeMode

#define levitree_SetFailSafeRequest_mode_ENUMTYPE levitree_VFDFailSafeMode

#define levitree_SetDriveModeRequest_drive_mode_ENUMTYPE levitree_VFDDriveMode




/* Initializer values for message structs */
#define levitree_VFDCommandRequest_init_default  {0, {levitree_SetFailSafeRequest_init_default}}
#define levitree_VFDCommandResponse_init_default {0}
#define levitree_VFDState_init_default           {0, 0, 0, 0, _levitree_VFDDriveMode_MIN, _levitree_VFDFailSafeMode_MIN, 0}
#define levitree_SetFailSafeRequest_init_default {_levitree_VFDFailSafeMode_MIN}
#define levitree_SetDriveModeRequest_init_default {_levitree_VFDDriveMode_MIN}
#define levitree_SetFrequencyRequest_init_default {0}
#define levitree_ClearAlarmRequest_init_default  {0}
#define levitree_VFDCommandRequest_init_zero     {0, {levitree_SetFailSafeRequest_init_zero}}
#define levitree_VFDCommandResponse_init_zero    {0}
#define levitree_VFDState_init_zero              {0, 0, 0, 0, _levitree_VFDDriveMode_MIN, _levitree_VFDFailSafeMode_MIN, 0}
#define levitree_SetFailSafeRequest_init_zero    {_levitree_VFDFailSafeMode_MIN}
#define levitree_SetDriveModeRequest_init_zero   {_levitree_VFDDriveMode_MIN}
#define levitree_SetFrequencyRequest_init_zero   {0}
#define levitree_ClearAlarmRequest_init_zero     {0}

/* Field tags (for use in manual encoding/decoding) */
#define levitree_VFDState_frequency_hz_tag       1
#define levitree_VFDState_power_w_tag            2
#define levitree_VFDState_current_a_tag          3
#define levitree_VFDState_voltage_v_tag          4
#define levitree_VFDState_drive_mode_tag         5
#define levitree_VFDState_fail_safe_mode_tag     6
#define levitree_VFDState_alarm_code_tag         7
#define levitree_SetFailSafeRequest_mode_tag     1
#define levitree_SetDriveModeRequest_drive_mode_tag 1
#define levitree_SetFrequencyRequest_frequency_hz_tag 1
#define levitree_VFDCommandRequest_set_fail_safe_tag 1
#define levitree_VFDCommandRequest_set_drive_mode_tag 2
#define levitree_VFDCommandRequest_set_frequency_tag 3
#define levitree_VFDCommandRequest_clear_alarm_tag 4

/* Struct field encoding specification for nanopb */
#define levitree_VFDCommandRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_fail_safe,command.set_fail_safe),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_drive_mode,command.set_drive_mode),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_frequency,command.set_frequency),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,clear_alarm,command.clear_alarm),   4)
#define levitree_VFDCommandRequest_CALLBACK NULL
#define levitree_VFDCommandRequest_DEFAULT NULL
#define levitree_VFDCommandRequest_command_set_fail_safe_MSGTYPE levitree_SetFailSafeRequest
#define levitree_VFDCommandRequest_command_set_drive_mode_MSGTYPE levitree_SetDriveModeRequest
#define levitree_VFDCommandRequest_command_set_frequency_MSGTYPE levitree_SetFrequencyRequest
#define levitree_VFDCommandRequest_command_clear_alarm_MSGTYPE levitree_ClearAlarmRequest

#define levitree_VFDCommandResponse_FIELDLIST(X, a) \

#define levitree_VFDCommandResponse_CALLBACK NULL
#define levitree_VFDCommandResponse_DEFAULT NULL

#define levitree_VFDState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    frequency_hz,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    power_w,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    current_a,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage_v,         4) \
X(a, STATIC,   SINGULAR, UENUM,    drive_mode,        5) \
X(a, STATIC,   SINGULAR, UENUM,    fail_safe_mode,    6) \
X(a, STATIC,   SINGULAR, INT32,    alarm_code,        7)
#define levitree_VFDState_CALLBACK NULL
#define levitree_VFDState_DEFAULT NULL

#define levitree_SetFailSafeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1)
#define levitree_SetFailSafeRequest_CALLBACK NULL
#define levitree_SetFailSafeRequest_DEFAULT NULL

#define levitree_SetDriveModeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    drive_mode,        1)
#define levitree_SetDriveModeRequest_CALLBACK NULL
#define levitree_SetDriveModeRequest_DEFAULT NULL

#define levitree_SetFrequencyRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    frequency_hz,      1)
#define levitree_SetFrequencyRequest_CALLBACK NULL
#define levitree_SetFrequencyRequest_DEFAULT NULL

#define levitree_ClearAlarmRequest_FIELDLIST(X, a) \

#define levitree_ClearAlarmRequest_CALLBACK NULL
#define levitree_ClearAlarmRequest_DEFAULT NULL

extern const pb_msgdesc_t levitree_VFDCommandRequest_msg;
extern const pb_msgdesc_t levitree_VFDCommandResponse_msg;
extern const pb_msgdesc_t levitree_VFDState_msg;
extern const pb_msgdesc_t levitree_SetFailSafeRequest_msg;
extern const pb_msgdesc_t levitree_SetDriveModeRequest_msg;
extern const pb_msgdesc_t levitree_SetFrequencyRequest_msg;
extern const pb_msgdesc_t levitree_ClearAlarmRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define levitree_VFDCommandRequest_fields &levitree_VFDCommandRequest_msg
#define levitree_VFDCommandResponse_fields &levitree_VFDCommandResponse_msg
#define levitree_VFDState_fields &levitree_VFDState_msg
#define levitree_SetFailSafeRequest_fields &levitree_SetFailSafeRequest_msg
#define levitree_SetDriveModeRequest_fields &levitree_SetDriveModeRequest_msg
#define levitree_SetFrequencyRequest_fields &levitree_SetFrequencyRequest_msg
#define levitree_ClearAlarmRequest_fields &levitree_ClearAlarmRequest_msg

/* Maximum encoded size of messages (where known) */
#define LEVITREE_DEVICE_VFD_PB_H_MAX_SIZE        levitree_VFDState_size
#define levitree_ClearAlarmRequest_size          0
#define levitree_SetDriveModeRequest_size        2
#define levitree_SetFailSafeRequest_size         2
#define levitree_SetFrequencyRequest_size        5
#define levitree_VFDCommandRequest_size          7
#define levitree_VFDCommandResponse_size         0
#define levitree_VFDState_size                   35

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
