/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "device_vfd.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(levitree_VFDCommandRequest, levitree_VFDCommandRequest, AUTO)


PB_BIND(levitree_VFDCommandResponse, levitree_VFDCommandResponse, AUTO)


PB_BIND(levitree_VFDState, levitree_VFDState, AUTO)


PB_BIND(levitree_SetFailSafeRequest, levitree_SetFailSafeRequest, AUTO)


PB_BIND(levitree_SetDriveModeRequest, levitree_SetDriveModeRequest, AUTO)


PB_BIND(levitree_SetFrequencyRequest, levitree_SetFrequencyRequest, AUTO)


PB_BIND(levitree_ClearAlarmRequest, levitree_ClearAlarmRequest, AUTO)







