/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "device_adc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(levitree_ADCCommandRequest, levitree_ADCCommandRequest, AUTO)


PB_BIND(levitree_ADCCommandResponse, levitree_ADCCommandResponse, AUTO)


PB_BIND(levitree_ADCChannelValue, levitree_ADCChannelValue, AUTO)


PB_BIND(levitree_ADCState, levitree_ADCState, AUTO)



