/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LEVITREE_DISCOVERY_PB_H_INCLUDED
#define PB_LEVITREE_DISCOVERY_PB_H_INCLUDED
#include <pb.h>
#include "enums.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _levitree_AttachedDevicesRequest {
    char dummy_field;
} levitree_AttachedDevicesRequest;

typedef struct _levitree_IdentifyActiveDeviceRequest {
    char dummy_field;
} levitree_IdentifyActiveDeviceRequest;

typedef struct _levitree_DeviceInfo {
    levitree_DeviceType device_type;
    uint32_t channels; /* number of channels available for this device */
    pb_byte_t mcu_id[16]; /* unique identifier for the device */
} levitree_DeviceInfo;

typedef struct _levitree_AttachedDevicesResponse {
    pb_size_t devices_count;
    levitree_DeviceInfo devices[32];
} levitree_AttachedDevicesResponse;

typedef struct _levitree_DiscoveryCommandResponse {
    pb_size_t which_message;
    union {
        levitree_AttachedDevicesResponse attached_devices_res;
        levitree_DeviceInfo identify_active_device_res;
    } message;
} levitree_DiscoveryCommandResponse;

typedef struct _levitree_SetChannelIdentityRequest {
    int32_t channel;
    bool active;
} levitree_SetChannelIdentityRequest;

typedef struct _levitree_DiscoveryCommandRequest {
    pb_size_t which_message;
    union {
        levitree_IdentifyActiveDeviceRequest identify_active_device_req;
        levitree_SetChannelIdentityRequest set_channel_identity_req;
        levitree_AttachedDevicesRequest attached_devices_req;
    } message;
} levitree_DiscoveryCommandRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define levitree_DiscoveryCommandRequest_init_default {0, {levitree_IdentifyActiveDeviceRequest_init_default}}
#define levitree_DiscoveryCommandResponse_init_default {0, {levitree_AttachedDevicesResponse_init_default}}
#define levitree_AttachedDevicesRequest_init_default {0}
#define levitree_AttachedDevicesResponse_init_default {0, {levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default, levitree_DeviceInfo_init_default}}
#define levitree_IdentifyActiveDeviceRequest_init_default {0}
#define levitree_DeviceInfo_init_default         {_levitree_DeviceType_MIN, 0, {0}}
#define levitree_SetChannelIdentityRequest_init_default {0, 0}
#define levitree_DiscoveryCommandRequest_init_zero {0, {levitree_IdentifyActiveDeviceRequest_init_zero}}
#define levitree_DiscoveryCommandResponse_init_zero {0, {levitree_AttachedDevicesResponse_init_zero}}
#define levitree_AttachedDevicesRequest_init_zero {0}
#define levitree_AttachedDevicesResponse_init_zero {0, {levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero, levitree_DeviceInfo_init_zero}}
#define levitree_IdentifyActiveDeviceRequest_init_zero {0}
#define levitree_DeviceInfo_init_zero            {_levitree_DeviceType_MIN, 0, {0}}
#define levitree_SetChannelIdentityRequest_init_zero {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define levitree_DeviceInfo_device_type_tag      1
#define levitree_DeviceInfo_channels_tag         2
#define levitree_DeviceInfo_mcu_id_tag           3
#define levitree_AttachedDevicesResponse_devices_tag 1
#define levitree_DiscoveryCommandResponse_attached_devices_res_tag 1
#define levitree_DiscoveryCommandResponse_identify_active_device_res_tag 2
#define levitree_SetChannelIdentityRequest_channel_tag 1
#define levitree_SetChannelIdentityRequest_active_tag 2
#define levitree_DiscoveryCommandRequest_identify_active_device_req_tag 1
#define levitree_DiscoveryCommandRequest_set_channel_identity_req_tag 3
#define levitree_DiscoveryCommandRequest_attached_devices_req_tag 4

/* Struct field encoding specification for nanopb */
#define levitree_DiscoveryCommandRequest_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,identify_active_device_req,message.identify_active_device_req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,set_channel_identity_req,message.set_channel_identity_req),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,attached_devices_req,message.attached_devices_req),   4)
#define levitree_DiscoveryCommandRequest_CALLBACK NULL
#define levitree_DiscoveryCommandRequest_DEFAULT NULL
#define levitree_DiscoveryCommandRequest_message_identify_active_device_req_MSGTYPE levitree_IdentifyActiveDeviceRequest
#define levitree_DiscoveryCommandRequest_message_set_channel_identity_req_MSGTYPE levitree_SetChannelIdentityRequest
#define levitree_DiscoveryCommandRequest_message_attached_devices_req_MSGTYPE levitree_AttachedDevicesRequest

#define levitree_DiscoveryCommandResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,attached_devices_res,message.attached_devices_res),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,identify_active_device_res,message.identify_active_device_res),   2)
#define levitree_DiscoveryCommandResponse_CALLBACK NULL
#define levitree_DiscoveryCommandResponse_DEFAULT NULL
#define levitree_DiscoveryCommandResponse_message_attached_devices_res_MSGTYPE levitree_AttachedDevicesResponse
#define levitree_DiscoveryCommandResponse_message_identify_active_device_res_MSGTYPE levitree_DeviceInfo

#define levitree_AttachedDevicesRequest_FIELDLIST(X, a) \

#define levitree_AttachedDevicesRequest_CALLBACK NULL
#define levitree_AttachedDevicesRequest_DEFAULT NULL

#define levitree_AttachedDevicesResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  devices,           1)
#define levitree_AttachedDevicesResponse_CALLBACK NULL
#define levitree_AttachedDevicesResponse_DEFAULT NULL
#define levitree_AttachedDevicesResponse_devices_MSGTYPE levitree_DeviceInfo

#define levitree_IdentifyActiveDeviceRequest_FIELDLIST(X, a) \

#define levitree_IdentifyActiveDeviceRequest_CALLBACK NULL
#define levitree_IdentifyActiveDeviceRequest_DEFAULT NULL

#define levitree_DeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    device_type,       1) \
X(a, STATIC,   SINGULAR, UINT32,   channels,          2) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, mcu_id,            3)
#define levitree_DeviceInfo_CALLBACK NULL
#define levitree_DeviceInfo_DEFAULT NULL

#define levitree_SetChannelIdentityRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    channel,           1) \
X(a, STATIC,   SINGULAR, BOOL,     active,            2)
#define levitree_SetChannelIdentityRequest_CALLBACK NULL
#define levitree_SetChannelIdentityRequest_DEFAULT NULL

extern const pb_msgdesc_t levitree_DiscoveryCommandRequest_msg;
extern const pb_msgdesc_t levitree_DiscoveryCommandResponse_msg;
extern const pb_msgdesc_t levitree_AttachedDevicesRequest_msg;
extern const pb_msgdesc_t levitree_AttachedDevicesResponse_msg;
extern const pb_msgdesc_t levitree_IdentifyActiveDeviceRequest_msg;
extern const pb_msgdesc_t levitree_DeviceInfo_msg;
extern const pb_msgdesc_t levitree_SetChannelIdentityRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define levitree_DiscoveryCommandRequest_fields &levitree_DiscoveryCommandRequest_msg
#define levitree_DiscoveryCommandResponse_fields &levitree_DiscoveryCommandResponse_msg
#define levitree_AttachedDevicesRequest_fields &levitree_AttachedDevicesRequest_msg
#define levitree_AttachedDevicesResponse_fields &levitree_AttachedDevicesResponse_msg
#define levitree_IdentifyActiveDeviceRequest_fields &levitree_IdentifyActiveDeviceRequest_msg
#define levitree_DeviceInfo_fields &levitree_DeviceInfo_msg
#define levitree_SetChannelIdentityRequest_fields &levitree_SetChannelIdentityRequest_msg

/* Maximum encoded size of messages (where known) */
#define LEVITREE_DISCOVERY_PB_H_MAX_SIZE         levitree_DiscoveryCommandResponse_size
#define levitree_AttachedDevicesRequest_size     0
#define levitree_AttachedDevicesResponse_size    896
#define levitree_DeviceInfo_size                 26
#define levitree_DiscoveryCommandRequest_size    15
#define levitree_DiscoveryCommandResponse_size   899
#define levitree_IdentifyActiveDeviceRequest_size 0
#define levitree_SetChannelIdentityRequest_size  13

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
