/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "discovery.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(levitree_DiscoveryCommandRequest, levitree_DiscoveryCommandRequest, AUTO)


PB_BIND(levitree_DiscoveryCommandResponse, levitree_DiscoveryCommandResponse, 2)


PB_BIND(levitree_AttachedDevicesRequest, levitree_AttachedDevicesRequest, AUTO)


PB_BIND(levitree_AttachedDevicesResponse, levitree_AttachedDevicesResponse, 2)


PB_BIND(levitree_IdentifyActiveDeviceRequest, levitree_IdentifyActiveDeviceRequest, AUTO)


PB_BIND(levitree_DeviceInfo, levitree_DeviceInfo, AUTO)


PB_BIND(levitree_SetChannelIdentityRequest, levitree_SetChannelIdentityRequest, AUTO)



