/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LEVITREE_ENUMS_PB_H_INCLUDED
#define PB_LEVITREE_ENUMS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _levitree_DeviceType {
    levitree_DeviceType_DEVICE_TYPE_UNSPECIFIED = 0,
    levitree_DeviceType_DEVICE_TYPE_BRAIN = 1,
    levitree_DeviceType_DEVICE_TYPE_HUB = 2,
    levitree_DeviceType_DEVICE_TYPE_ADC_2 = 3,
    levitree_DeviceType_DEVICE_TYPE_ADC_4 = 4,
    levitree_DeviceType_DEVICE_TYPE_ADC_8 = 5,
    levitree_DeviceType_DEVICE_TYPE_VFD = 6
} levitree_DeviceType;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _levitree_DeviceType_MIN levitree_DeviceType_DEVICE_TYPE_UNSPECIFIED
#define _levitree_DeviceType_MAX levitree_DeviceType_DEVICE_TYPE_VFD
#define _levitree_DeviceType_ARRAYSIZE ((levitree_DeviceType)(levitree_DeviceType_DEVICE_TYPE_VFD+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
