/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LEVITREE_HEARTBEAT_PB_H_INCLUDED
#define PB_LEVITREE_HEARTBEAT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _levitree_HeartbeatRequest {
    char dummy_field;
} levitree_HeartbeatRequest;

typedef struct _levitree_HeartbeatResponse {
    int64_t timestamp; /* Timestamp in milliseconds since epoch */
} levitree_HeartbeatResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define levitree_HeartbeatRequest_init_default   {0}
#define levitree_HeartbeatResponse_init_default  {0}
#define levitree_HeartbeatRequest_init_zero      {0}
#define levitree_HeartbeatResponse_init_zero     {0}

/* Field tags (for use in manual encoding/decoding) */
#define levitree_HeartbeatResponse_timestamp_tag 1

/* Struct field encoding specification for nanopb */
#define levitree_HeartbeatRequest_FIELDLIST(X, a) \

#define levitree_HeartbeatRequest_CALLBACK NULL
#define levitree_HeartbeatRequest_DEFAULT NULL

#define levitree_HeartbeatResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         1)
#define levitree_HeartbeatResponse_CALLBACK NULL
#define levitree_HeartbeatResponse_DEFAULT NULL

extern const pb_msgdesc_t levitree_HeartbeatRequest_msg;
extern const pb_msgdesc_t levitree_HeartbeatResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define levitree_HeartbeatRequest_fields &levitree_HeartbeatRequest_msg
#define levitree_HeartbeatResponse_fields &levitree_HeartbeatResponse_msg

/* Maximum encoded size of messages (where known) */
#define LEVITREE_HEARTBEAT_PB_H_MAX_SIZE         levitree_HeartbeatResponse_size
#define levitree_HeartbeatRequest_size           0
#define levitree_HeartbeatResponse_size          11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
