/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "levitree.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(levitree_Endpoint, levitree_Endpoint, AUTO)


PB_BIND(levitree_RoutableMessage, levitree_RoutableMessage, 2)


PB_BIND(levitree_RoutingDeviceState, levitree_RoutingDeviceState, AUTO)


PB_BIND(levitree_GPSState, levitree_GPSState, AUTO)


PB_BIND(levitree_SystemInfoRequest, levitree_SystemInfoRequest, AUTO)


PB_BIND(levitree_SystemInfoResponse, levitree_SystemInfoResponse, AUTO)


PB_BIND(levitree_StateUpdateRequest, levitree_StateUpdateRequest, AUTO)


PB_BIND(levitree_StateUpdateResponse, levitree_StateUpdateResponse, AUTO)


PB_BIND(levitree_AcknowledgeResponse, levitree_AcknowledgeResponse, AUTO)


PB_BIND(levitree_ErrorResponse, levitree_ErrorResponse, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

