/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LEVITREE_LEVITREE_PB_H_INCLUDED
#define PB_LEVITREE_LEVITREE_PB_H_INCLUDED
#include <pb.h>
#include "device_adc.pb.h"
#include "device_vfd.pb.h"
#include "discovery.pb.h"
#include "enums.pb.h"
#include "heartbeat.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _levitree_Endpoint {
    pb_byte_t mcu_id[16];
} levitree_Endpoint;

typedef struct _levitree_GPSState {
    bool has_gps; /* Indicates if GPS data is available */
    double latitude; /* Latitude in degrees */
    double longitude; /* Longitude in degrees */
    float altitude; /* Altitude in meters */
    float speed; /* Speed in m/s */
    float heading; /* Heading in degrees */
    int32_t satellites; /* Number of satellites used for the fix */
} levitree_GPSState;

typedef struct _levitree_RoutingDeviceState {
    bool has_gps_state;
    levitree_GPSState gps_state; /* GPS state information */
} levitree_RoutingDeviceState;

typedef struct _levitree_SystemInfoRequest {
    char dummy_field;
} levitree_SystemInfoRequest;

typedef struct _levitree_SystemInfoResponse {
    int32_t firmware_version;
    int32_t hardware_version;
    char hardware_codename[32]; /* e.g. "levitree_v1" */
    char software_codename[32]; /* e.g. "levitree_software_v1" */
    levitree_DeviceType device_type; /* Type of the device */
} levitree_SystemInfoResponse;

typedef struct _levitree_StateUpdateRequest {
    char dummy_field;
} levitree_StateUpdateRequest;

typedef struct _levitree_StateUpdateResponse {
    pb_size_t which_message;
    union {
        levitree_ADCState adc_state; /* done */
        levitree_VFDState vfd_state; /* done */
        levitree_RoutingDeviceState routing_device_state; /* done */
    } message;
} levitree_StateUpdateResponse;

typedef struct _levitree_AcknowledgeResponse {
    char dummy_field;
} levitree_AcknowledgeResponse;

typedef struct _levitree_ErrorResponse {
    char error_message[32]; /* Description of the error */
} levitree_ErrorResponse;

typedef struct _levitree_RoutableMessage {
    bool has_source;
    levitree_Endpoint source;
    bool has_destination;
    levitree_Endpoint destination;
    pb_size_t which_payload;
    union {
        levitree_SystemInfoRequest system_info_req;
        levitree_SystemInfoResponse system_info_res;
        levitree_DiscoveryCommandRequest discovery_command_req;
        levitree_DiscoveryCommandResponse discovery_command_res;
        levitree_StateUpdateRequest state_update_req;
        levitree_StateUpdateResponse state_update_res;
        levitree_VFDCommandRequest vfd_command_req;
        levitree_VFDCommandResponse vfd_command_res;
        levitree_ADCCommandRequest adc_command_req;
        levitree_ADCCommandResponse adc_command_res;
        levitree_HeartbeatRequest heartbeat;
        levitree_HeartbeatResponse heartbeat_response;
        levitree_AcknowledgeResponse acknowledge_response;
        levitree_ErrorResponse error_response;
    } payload;
} levitree_RoutableMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define levitree_Endpoint_init_default           {{0}}
#define levitree_RoutableMessage_init_default    {false, levitree_Endpoint_init_default, false, levitree_Endpoint_init_default, 0, {levitree_SystemInfoRequest_init_default}}
#define levitree_RoutingDeviceState_init_default {false, levitree_GPSState_init_default}
#define levitree_GPSState_init_default           {0, 0, 0, 0, 0, 0, 0}
#define levitree_SystemInfoRequest_init_default  {0}
#define levitree_SystemInfoResponse_init_default {0, 0, "", "", _levitree_DeviceType_MIN}
#define levitree_StateUpdateRequest_init_default {0}
#define levitree_StateUpdateResponse_init_default {0, {levitree_ADCState_init_default}}
#define levitree_AcknowledgeResponse_init_default {0}
#define levitree_ErrorResponse_init_default      {""}
#define levitree_Endpoint_init_zero              {{0}}
#define levitree_RoutableMessage_init_zero       {false, levitree_Endpoint_init_zero, false, levitree_Endpoint_init_zero, 0, {levitree_SystemInfoRequest_init_zero}}
#define levitree_RoutingDeviceState_init_zero    {false, levitree_GPSState_init_zero}
#define levitree_GPSState_init_zero              {0, 0, 0, 0, 0, 0, 0}
#define levitree_SystemInfoRequest_init_zero     {0}
#define levitree_SystemInfoResponse_init_zero    {0, 0, "", "", _levitree_DeviceType_MIN}
#define levitree_StateUpdateRequest_init_zero    {0}
#define levitree_StateUpdateResponse_init_zero   {0, {levitree_ADCState_init_zero}}
#define levitree_AcknowledgeResponse_init_zero   {0}
#define levitree_ErrorResponse_init_zero         {""}

/* Field tags (for use in manual encoding/decoding) */
#define levitree_Endpoint_mcu_id_tag             1
#define levitree_GPSState_has_gps_tag            1
#define levitree_GPSState_latitude_tag           2
#define levitree_GPSState_longitude_tag          3
#define levitree_GPSState_altitude_tag           4
#define levitree_GPSState_speed_tag              5
#define levitree_GPSState_heading_tag            6
#define levitree_GPSState_satellites_tag         7
#define levitree_RoutingDeviceState_gps_state_tag 1
#define levitree_SystemInfoResponse_firmware_version_tag 1
#define levitree_SystemInfoResponse_hardware_version_tag 2
#define levitree_SystemInfoResponse_hardware_codename_tag 3
#define levitree_SystemInfoResponse_software_codename_tag 4
#define levitree_SystemInfoResponse_device_type_tag 5
#define levitree_StateUpdateResponse_adc_state_tag 1
#define levitree_StateUpdateResponse_vfd_state_tag 2
#define levitree_StateUpdateResponse_routing_device_state_tag 3
#define levitree_ErrorResponse_error_message_tag 1
#define levitree_RoutableMessage_source_tag      1
#define levitree_RoutableMessage_destination_tag 2
#define levitree_RoutableMessage_system_info_req_tag 3
#define levitree_RoutableMessage_system_info_res_tag 4
#define levitree_RoutableMessage_discovery_command_req_tag 10
#define levitree_RoutableMessage_discovery_command_res_tag 11
#define levitree_RoutableMessage_state_update_req_tag 15
#define levitree_RoutableMessage_state_update_res_tag 16
#define levitree_RoutableMessage_vfd_command_req_tag 17
#define levitree_RoutableMessage_vfd_command_res_tag 18
#define levitree_RoutableMessage_adc_command_req_tag 19
#define levitree_RoutableMessage_adc_command_res_tag 20
#define levitree_RoutableMessage_heartbeat_tag   251
#define levitree_RoutableMessage_heartbeat_response_tag 252
#define levitree_RoutableMessage_acknowledge_response_tag 253
#define levitree_RoutableMessage_error_response_tag 254

/* Struct field encoding specification for nanopb */
#define levitree_Endpoint_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, mcu_id,            1)
#define levitree_Endpoint_CALLBACK NULL
#define levitree_Endpoint_DEFAULT NULL

#define levitree_RoutableMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  source,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  destination,       2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,system_info_req,payload.system_info_req),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,system_info_res,payload.system_info_res),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,discovery_command_req,payload.discovery_command_req),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,discovery_command_res,payload.discovery_command_res),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,state_update_req,payload.state_update_req),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,state_update_res,payload.state_update_res),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,vfd_command_req,payload.vfd_command_req),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,vfd_command_res,payload.vfd_command_res),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adc_command_req,payload.adc_command_req),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,adc_command_res,payload.adc_command_res),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,heartbeat,payload.heartbeat), 251) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,heartbeat_response,payload.heartbeat_response), 252) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,acknowledge_response,payload.acknowledge_response), 253) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,error_response,payload.error_response), 254)
#define levitree_RoutableMessage_CALLBACK NULL
#define levitree_RoutableMessage_DEFAULT NULL
#define levitree_RoutableMessage_source_MSGTYPE levitree_Endpoint
#define levitree_RoutableMessage_destination_MSGTYPE levitree_Endpoint
#define levitree_RoutableMessage_payload_system_info_req_MSGTYPE levitree_SystemInfoRequest
#define levitree_RoutableMessage_payload_system_info_res_MSGTYPE levitree_SystemInfoResponse
#define levitree_RoutableMessage_payload_discovery_command_req_MSGTYPE levitree_DiscoveryCommandRequest
#define levitree_RoutableMessage_payload_discovery_command_res_MSGTYPE levitree_DiscoveryCommandResponse
#define levitree_RoutableMessage_payload_state_update_req_MSGTYPE levitree_StateUpdateRequest
#define levitree_RoutableMessage_payload_state_update_res_MSGTYPE levitree_StateUpdateResponse
#define levitree_RoutableMessage_payload_vfd_command_req_MSGTYPE levitree_VFDCommandRequest
#define levitree_RoutableMessage_payload_vfd_command_res_MSGTYPE levitree_VFDCommandResponse
#define levitree_RoutableMessage_payload_adc_command_req_MSGTYPE levitree_ADCCommandRequest
#define levitree_RoutableMessage_payload_adc_command_res_MSGTYPE levitree_ADCCommandResponse
#define levitree_RoutableMessage_payload_heartbeat_MSGTYPE levitree_HeartbeatRequest
#define levitree_RoutableMessage_payload_heartbeat_response_MSGTYPE levitree_HeartbeatResponse
#define levitree_RoutableMessage_payload_acknowledge_response_MSGTYPE levitree_AcknowledgeResponse
#define levitree_RoutableMessage_payload_error_response_MSGTYPE levitree_ErrorResponse

#define levitree_RoutingDeviceState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gps_state,         1)
#define levitree_RoutingDeviceState_CALLBACK NULL
#define levitree_RoutingDeviceState_DEFAULT NULL
#define levitree_RoutingDeviceState_gps_state_MSGTYPE levitree_GPSState

#define levitree_GPSState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_gps,           1) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude,          2) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude,          4) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             5) \
X(a, STATIC,   SINGULAR, FLOAT,    heading,           6) \
X(a, STATIC,   SINGULAR, INT32,    satellites,        7)
#define levitree_GPSState_CALLBACK NULL
#define levitree_GPSState_DEFAULT NULL

#define levitree_SystemInfoRequest_FIELDLIST(X, a) \

#define levitree_SystemInfoRequest_CALLBACK NULL
#define levitree_SystemInfoRequest_DEFAULT NULL

#define levitree_SystemInfoResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    firmware_version,   1) \
X(a, STATIC,   SINGULAR, INT32,    hardware_version,   2) \
X(a, STATIC,   SINGULAR, STRING,   hardware_codename,   3) \
X(a, STATIC,   SINGULAR, STRING,   software_codename,   4) \
X(a, STATIC,   SINGULAR, UENUM,    device_type,       5)
#define levitree_SystemInfoResponse_CALLBACK NULL
#define levitree_SystemInfoResponse_DEFAULT NULL

#define levitree_StateUpdateRequest_FIELDLIST(X, a) \

#define levitree_StateUpdateRequest_CALLBACK NULL
#define levitree_StateUpdateRequest_DEFAULT NULL

#define levitree_StateUpdateResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,adc_state,message.adc_state),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,vfd_state,message.vfd_state),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,routing_device_state,message.routing_device_state),   3)
#define levitree_StateUpdateResponse_CALLBACK NULL
#define levitree_StateUpdateResponse_DEFAULT NULL
#define levitree_StateUpdateResponse_message_adc_state_MSGTYPE levitree_ADCState
#define levitree_StateUpdateResponse_message_vfd_state_MSGTYPE levitree_VFDState
#define levitree_StateUpdateResponse_message_routing_device_state_MSGTYPE levitree_RoutingDeviceState

#define levitree_AcknowledgeResponse_FIELDLIST(X, a) \

#define levitree_AcknowledgeResponse_CALLBACK NULL
#define levitree_AcknowledgeResponse_DEFAULT NULL

#define levitree_ErrorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   error_message,     1)
#define levitree_ErrorResponse_CALLBACK NULL
#define levitree_ErrorResponse_DEFAULT NULL

extern const pb_msgdesc_t levitree_Endpoint_msg;
extern const pb_msgdesc_t levitree_RoutableMessage_msg;
extern const pb_msgdesc_t levitree_RoutingDeviceState_msg;
extern const pb_msgdesc_t levitree_GPSState_msg;
extern const pb_msgdesc_t levitree_SystemInfoRequest_msg;
extern const pb_msgdesc_t levitree_SystemInfoResponse_msg;
extern const pb_msgdesc_t levitree_StateUpdateRequest_msg;
extern const pb_msgdesc_t levitree_StateUpdateResponse_msg;
extern const pb_msgdesc_t levitree_AcknowledgeResponse_msg;
extern const pb_msgdesc_t levitree_ErrorResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define levitree_Endpoint_fields &levitree_Endpoint_msg
#define levitree_RoutableMessage_fields &levitree_RoutableMessage_msg
#define levitree_RoutingDeviceState_fields &levitree_RoutingDeviceState_msg
#define levitree_GPSState_fields &levitree_GPSState_msg
#define levitree_SystemInfoRequest_fields &levitree_SystemInfoRequest_msg
#define levitree_SystemInfoResponse_fields &levitree_SystemInfoResponse_msg
#define levitree_StateUpdateRequest_fields &levitree_StateUpdateRequest_msg
#define levitree_StateUpdateResponse_fields &levitree_StateUpdateResponse_msg
#define levitree_AcknowledgeResponse_fields &levitree_AcknowledgeResponse_msg
#define levitree_ErrorResponse_fields &levitree_ErrorResponse_msg

/* Maximum encoded size of messages (where known) */
#define LEVITREE_LEVITREE_PB_H_MAX_SIZE          levitree_RoutableMessage_size
#define levitree_AcknowledgeResponse_size        0
#define levitree_Endpoint_size                   18
#define levitree_ErrorResponse_size              33
#define levitree_GPSState_size                   46
#define levitree_RoutableMessage_size            942
#define levitree_RoutingDeviceState_size         48
#define levitree_StateUpdateRequest_size         0
#define levitree_StateUpdateResponse_size        195
#define levitree_SystemInfoRequest_size          0
#define levitree_SystemInfoResponse_size         90

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
